site_name: pyKMC
theme:
  name: material
  features:
  - content.code.copy  # Ajoute un bouton "Copier" sur les blocs de code
  - content.code.annotate  # Active le surlignage de syntaxe
  - content.code.highlight  # Améliore le rendu du code

nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
  - Troubleshooting: troubleshooting.md
  - Tutorial: 
      - pyKMC Workflow : 0-pyKMC-workflow.md 
  - API Reference: reference.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: false
            heading_level: 2
            members_order: alphabetical
            separate_signature: true
            show_docstring_examples: true
            show_root_heading: true

site_url: https://hugomoison.github.io/pyKMC/
