site_name: pyKMC
theme:
  name: material
  font:
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-orange
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-orange
      accent: red
      toggle:
        icon: material/brightness-3
        name: Switch to light mode

  features:
  - content.code.copy
  - content.code.annotate
  - content.code.highlight

nav:
  - Home: index.md
  - Getting Started:
      - Installation: install/installation.md
      - macOS Compile Instructions: install/pykmc_mac_Compile_Instructions.md
      - Linux Compile Instructions: install/pykmc_linux_Compile_Instructions.md
      - User Guide: user_guide.md
  - Concepts:
      - Algorithm Overview: general_algorithm.md
      - Basins: basins.md
      - Active Volumes: active_volumes.md
      - Symmetries: symmetries.md
  - KMC Parameters: parameters.md
  - Troubleshooting: troubleshooting.md
  - Developer Guide: developer_guide.md
  - API Reference:
      - System: api/system.md
      - NeighborsList: api/neighbors_list.md
      - AtomicEnvironment: api/atomic_environment.md
      - Config: api/config.md
      - Log: api/log.md
      - Algorithms: api/algorithms.md
      - KMC: api/kmc.md
      - Environments: api/environments.md
      - EventTable: api/event_table.md
      - EventSearch: api/eventsearch.md
      - Bias: api/bias.md
      - Refinement: api/refinement.md
      - PointSetRegistration: api/point_set_registration.md
      - Symmetries: api/symmetries.md
      - RateConstant: api/rate_constant.md
      - Basins: api/basins.md
      - ActiveVolume: api/active_volume.md
      - Initialize: api/initialized.md
      - Result: api/result.md
      - Info: api/info_simulation.md
      - Utils: api/utils.md
      - Run: api/run.md

markdown_extensions:
  - pymdownx.arithmatex:
  - mdx_include:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

extra:
  version:
    provider: mike

plugins:
  - mike:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: false
            heading_level: 2
            members_order: alphabetical
            separate_signature: true
            show_docstring_examples: true
            show_root_heading: true
  - search:
  - mkdocs-jupyter:
extra_css:
  - stylesheets/gruvbox.css

use_directory_urls: false
site_url: https://hugomoison.github.io/pyKMC/
